[package]
name = "backoff"
version = "0.1.7-alpha.0"
authors = ["Tibor Benke <ihrwein@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/ihrwein/backoff"
homepage = "https://github.com/ihrwein/backoff"
documentation = "https://docs.rs/backoff"
categories = ["network-programming"]
description = """
Retry operations with exponential backoff policy.
"""

[badges]
travis-ci = { repository = "ihrwein/backoff" }

[dependencies]
instant = "0.1"
rand = "0.7"

[dev-dependencies]
reqwest = "0.9.10"

[features]
default = []
stdweb = ["instant/stdweb", "rand/stdweb"]
wasm-bindgen = ["instant/wasm-bindgen", "rand/wasm-bindgen"]
